/** Demo observations covering IDE, framework, cloud, MCP, local LLM, browser, autonomous agents */
export function demoObservations(tenantId) {
  const now = new Date().toISOString();
  return [
    {
      collector_id: "demo",
      fingerprint: "ide:cursor:alex.chen:laptop-42",
      name: "Cursor Agent — alex.chen",
      category: "ide",
      owner: "alex.chen@acme.com",
      device: "laptop-42",
      hostname: "laptop-42.acme.local",
      ip: "10.20.1.42",
      operating_system: "macOS 14.5",
      department: "Engineering",
      business_unit: "Product",
      location: "San Francisco",
      repository: "github.com/acme/payments-api",
      framework: null,
      programming_language: "TypeScript",
      model: "claude-sonnet-4",
      provider: "anthropic",
      version: "0.48.0",
      deployment_type: "ide",
      ide: "Cursor",
      running_status: "running",
      memory_usage_mb: 820,
      cpu_usage_pct: 12,
      mcp_connections: ["filesystem", "github", "postgres"],
      tools: ["edit_file", "run_terminal", "codebase_search"],
      internet_access: true,
      filesystem_access: true,
      github_access: true,
      database_access: true,
      execution_capability: "code_execution",
      risk_indicators: ["filesystem_write", "shell_access"],
      confidence_score: 0.92,
      relationships: [
        { rel_type: "OWNS", to_type: "Developer", to_key: "alex.chen@acme.com", to_name: "Alex Chen" },
        { rel_type: "RUNS_IN", to_type: "IDE", to_key: "cursor", to_name: "Cursor" },
        { rel_type: "RUNS_ON", to_type: "Device", to_key: "laptop-42", to_name: "laptop-42" },
        { rel_type: "INVOKES_MODEL", to_type: "Model", to_key: "claude-sonnet-4", to_name: "claude-sonnet-4" },
        { rel_type: "CONNECTS_MCP", to_type: "MCPServer", to_key: "mcp-github", to_name: "GitHub MCP" },
        { rel_type: "SOURCED_FROM", to_type: "Repository", to_key: "acme/payments-api", to_name: "payments-api" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "ide:copilot:jamie.lee:ws-17",
      name: "GitHub Copilot — jamie.lee",
      category: "ide",
      owner: "jamie.lee@acme.com",
      hostname: "ws-17.acme.local",
      department: "Engineering",
      business_unit: "Platform",
      ide: "VS Code",
      model: "gpt-4.1",
      provider: "openai",
      deployment_type: "ide",
      programming_language: "Python",
      running_status: "running",
      tools: ["inline_complete", "chat"],
      github_access: true,
      confidence_score: 0.88,
      relationships: [
        { rel_type: "OWNS", to_type: "Developer", to_key: "jamie.lee@acme.com", to_name: "Jamie Lee" },
        { rel_type: "RUNS_IN", to_type: "IDE", to_key: "vscode", to_name: "VS Code" },
        { rel_type: "INVOKES_MODEL", to_type: "Model", to_key: "gpt-4.1", to_name: "gpt-4.1" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "fw:langgraph:support-triage:prod",
      name: "Support Triage Graph",
      category: "framework",
      owner: "ai-platform@acme.com",
      department: "AI Platform",
      business_unit: "Technology",
      repository: "github.com/acme/support-triage",
      framework: "LangGraph",
      programming_language: "Python",
      model: "gpt-4o",
      provider: "openai",
      deployment_type: "cloud",
      cloud_provider: "aws",
      region: "us-east-1",
      container: "support-triage:1.4.2",
      running_status: "running",
      vector_database: "pinecone",
      tools: ["ticket_lookup", "kb_search", "escalate"],
      slack_access: true,
      email_access: true,
      database_access: true,
      internet_access: true,
      risk_indicators: ["pii_tickets", "external_email"],
      confidence_score: 0.95,
      relationships: [
        { rel_type: "OWNS", to_type: "Developer", to_key: "ai-platform@acme.com", to_name: "AI Platform" },
        { rel_type: "INVOKES_MODEL", to_type: "Model", to_key: "gpt-4o", to_name: "gpt-4o" },
        { rel_type: "USES_TOOL", to_type: "Tool", to_key: "kb_search", to_name: "kb_search" },
        { rel_type: "READS_WRITES", to_type: "Database", to_key: "pinecone-support", to_name: "pinecone-support" },
        { rel_type: "DEPLOYED_IN", to_type: "CloudResource", to_key: "ecs-support-triage", to_name: "ECS support-triage" },
        { rel_type: "ACCESSES", to_type: "ExternalService", to_key: "slack", to_name: "Slack" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "fw:crewai:research-crew:dev",
      name: "Market Research Crew",
      category: "framework",
      owner: "priya.nair@acme.com",
      department: "Strategy",
      business_unit: "Corporate",
      framework: "CrewAI",
      programming_language: "Python",
      model: "claude-opus-4",
      provider: "anthropic",
      deployment_type: "local",
      hostname: "devbox-9.acme.local",
      running_status: "scheduled",
      tools: ["web_search", "summarize", "write_report"],
      internet_access: true,
      browser_access: true,
      confidence_score: 0.84,
      relationships: [
        { rel_type: "OWNS", to_type: "Developer", to_key: "priya.nair@acme.com", to_name: "Priya Nair" },
        { rel_type: "INVOKES_MODEL", to_type: "Model", to_key: "claude-opus-4", to_name: "claude-opus-4" },
        { rel_type: "USES_TOOL", to_type: "Tool", to_key: "web_search", to_name: "web_search" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "cloud:bedrock:claims-agent:us-west-2",
      name: "Claims Processing Agent",
      category: "cloud",
      owner: "claims-eng@acme.com",
      department: "Claims",
      business_unit: "Insurance Ops",
      framework: "AWS Bedrock Agents",
      model: "anthropic.claude-3-5-sonnet",
      provider: "aws",
      deployment_type: "cloud",
      cloud_provider: "aws",
      region: "us-west-2",
      endpoint: "bedrock-agent-runtime.us-west-2.amazonaws.com",
      running_status: "running",
      database_access: true,
      internet_access: false,
      risk_indicators: ["regulated_data"],
      confidence_score: 0.91,
      relationships: [
        { rel_type: "DEPLOYED_IN", to_type: "CloudResource", to_key: "bedrock-claims", to_name: "Bedrock Claims Agent" },
        { rel_type: "INVOKES_MODEL", to_type: "Model", to_key: "claude-3-5-sonnet", to_name: "claude-3-5-sonnet" },
        { rel_type: "CALLS", to_type: "API", to_key: "claims-api", to_name: "Claims API" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "cloud:azure-foundry:hr-copilot:eastus",
      name: "HR Copilot (Azure AI Foundry)",
      category: "cloud",
      owner: "hr-it@acme.com",
      department: "HR",
      business_unit: "People",
      model: "gpt-4o",
      provider: "azure",
      cloud_provider: "azure",
      region: "eastus",
      deployment_type: "cloud",
      running_status: "running",
      email_access: true,
      calendar_access: true,
      confidence_score: 0.87,
      relationships: [
        { rel_type: "DEPLOYED_IN", to_type: "CloudResource", to_key: "foundry-hr", to_name: "Azure AI Foundry HR" },
        { rel_type: "INVOKES_MODEL", to_type: "Model", to_key: "gpt-4o", to_name: "gpt-4o" },
        { rel_type: "ACCESSES", to_type: "ExternalService", to_key: "m365", to_name: "Microsoft 365" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "mcp:server:postgres-tools:shared",
      name: "Postgres MCP Server",
      category: "mcp",
      owner: "platform@acme.com",
      department: "Platform",
      business_unit: "Technology",
      deployment_type: "mcp",
      endpoint: "stdio://postgres-mcp",
      tools: ["query", "schema", "explain"],
      database_access: true,
      running_status: "running",
      confidence_score: 0.9,
      mcp_connections: ["postgres"],
      relationships: [
        { rel_type: "EXPOSES_TOOL", to_type: "Tool", to_key: "query", to_name: "query" },
        { rel_type: "READS_WRITES", to_type: "Database", to_key: "acme-prod-pg", to_name: "acme-prod-pg" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "local:ollama:llama3:devbox-3",
      name: "Ollama llama3 (local)",
      category: "local_llm",
      owner: "sam.park@acme.com",
      hostname: "devbox-3.acme.local",
      department: "Engineering",
      business_unit: "Product",
      model: "llama3.1:70b",
      provider: "ollama",
      deployment_type: "local",
      running_status: "running",
      memory_usage_mb: 42000,
      internet_access: false,
      confidence_score: 0.93,
      relationships: [
        { rel_type: "OWNS", to_type: "Developer", to_key: "sam.park@acme.com", to_name: "Sam Park" },
        { rel_type: "RUNS_ON", to_type: "Device", to_key: "devbox-3", to_name: "devbox-3" },
        { rel_type: "INVOKES_MODEL", to_type: "Model", to_key: "llama3.1:70b", to_name: "llama3.1:70b" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "browser:extension:perplexity:chrome:alex",
      name: "Perplexity Chrome Extension",
      category: "browser",
      owner: "alex.chen@acme.com",
      department: "Engineering",
      browser_access: true,
      internet_access: true,
      deployment_type: "browser",
      provider: "perplexity",
      running_status: "running",
      confidence_score: 0.7,
      risk_indicators: ["unmanaged_saas"],
      relationships: [
        { rel_type: "OWNS", to_type: "Developer", to_key: "alex.chen@acme.com", to_name: "Alex Chen" },
        { rel_type: "ACCESSES", to_type: "ExternalService", to_key: "perplexity", to_name: "Perplexity" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "auto:nightly-refactor:ci",
      name: "Nightly Refactor Agent",
      category: "autonomous",
      owner: "devops@acme.com",
      department: "DevOps",
      business_unit: "Technology",
      framework: "OpenAI Agents SDK",
      programming_language: "TypeScript",
      model: "o3",
      provider: "openai",
      deployment_type: "cloud",
      cloud_provider: "gcp",
      region: "us-central1",
      running_status: "scheduled",
      repository: "github.com/acme/monorepo",
      github_access: true,
      filesystem_access: true,
      execution_capability: "pr_creation",
      confidence_score: 0.86,
      relationships: [
        { rel_type: "SOURCED_FROM", to_type: "Repository", to_key: "acme/monorepo", to_name: "monorepo" },
        { rel_type: "INVOKES_MODEL", to_type: "Model", to_key: "o3", to_name: "o3" },
        { rel_type: "ACCESSES", to_type: "ExternalService", to_key: "github", to_name: "GitHub" },
        { rel_type: "DEPLOYED_IN", to_type: "CloudResource", to_key: "cloudrun-refactor", to_name: "Cloud Run refactor" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "k8s:crew:doc-ingest:ns-ai",
      name: "Doc Ingest Agent (K8s)",
      category: "container",
      owner: "data-platform@acme.com",
      department: "Data",
      business_unit: "Technology",
      framework: "LlamaIndex",
      programming_language: "Python",
      model: "text-embedding-3-large",
      provider: "openai",
      deployment_type: "container",
      cloud_provider: "azure",
      region: "westus2",
      container: "doc-ingest:2.1.0",
      vector_database: "azure-ai-search",
      running_status: "running",
      confidence_score: 0.89,
      relationships: [
        { rel_type: "DEPLOYED_IN", to_type: "CloudResource", to_key: "aks-ai", to_name: "AKS ai namespace" },
        { rel_type: "READS_WRITES", to_type: "Database", to_key: "azure-ai-search", to_name: "Azure AI Search" },
        { rel_type: "INVOKES_MODEL", to_type: "Model", to_key: "text-embedding-3-large", to_name: "text-embedding-3-large" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "saas:notion-ai:workspace",
      name: "Notion AI Workspace Agent",
      category: "saas",
      owner: "knowledge@acme.com",
      department: "Knowledge Mgmt",
      business_unit: "Corporate",
      provider: "notion",
      deployment_type: "saas",
      running_status: "running",
      internet_access: true,
      confidence_score: 0.75,
      risk_indicators: ["saas_shadow"],
      relationships: [
        { rel_type: "ACCESSES", to_type: "ExternalService", to_key: "notion", to_name: "Notion" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "saas:m365_copilot:tenant-demo",
      name: "Microsoft 365 Copilot (demo tenant)",
      category: "saas",
      owner: "m365-admins@acme.com",
      department: "IT",
      business_unit: "Corporate",
      provider: "m365_copilot",
      framework: "Microsoft 365 Copilot",
      model: "microsoft-copilot",
      deployment_type: "saas",
      running_status: "running",
      confidence_score: 0.9,
      metadata: { managedPlatformAgent: true, platform: "m365_copilot", inventoryClass: "platform_agent" },
      relationships: [
        { rel_type: "RUNS_ON", to_type: "SaaSPlatform", to_key: "saas-m365_copilot", to_name: "Microsoft 365 Copilot" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "saas:salesforce:agentforce:case-triage",
      name: "Salesforce Agentforce — Case Triage",
      category: "saas",
      owner: "crm-ops@acme.com",
      department: "Customer Success",
      business_unit: "Revenue",
      provider: "salesforce",
      framework: "Salesforce Agentforce",
      model: "salesforce-agentforce",
      deployment_type: "saas",
      running_status: "running",
      confidence_score: 0.91,
      metadata: { managedPlatformAgent: true, platform: "salesforce", inventoryClass: "platform_agent" },
      relationships: [
        { rel_type: "RUNS_ON", to_type: "SaaSPlatform", to_key: "saas-salesforce", to_name: "Salesforce Agentforce" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "saas:workday:illuminate:hr-assist",
      name: "Workday Illuminate — HR Assist",
      category: "saas",
      owner: "hris@acme.com",
      department: "People Ops",
      business_unit: "Corporate",
      provider: "workday",
      framework: "Workday Illuminate",
      model: "workday-illuminate",
      deployment_type: "saas",
      running_status: "running",
      confidence_score: 0.89,
      metadata: { managedPlatformAgent: true, platform: "workday", inventoryClass: "platform_agent" },
      relationships: [
        { rel_type: "RUNS_ON", to_type: "SaaSPlatform", to_key: "saas-workday", to_name: "Workday Illuminate" }
      ]
    },
    {
      collector_id: "demo",
      fingerprint: "saas:servicenow:now-assist:it-virtual-agent",
      name: "ServiceNow Now Assist — IT Virtual Agent",
      category: "saas",
      owner: "itsm@acme.com",
      department: "IT Service Management",
      business_unit: "Technology",
      provider: "servicenow",
      framework: "ServiceNow Now Assist",
      model: "servicenow-now-assist",
      deployment_type: "saas",
      running_status: "running",
      confidence_score: 0.9,
      metadata: { managedPlatformAgent: true, platform: "servicenow", inventoryClass: "platform_agent" },
      relationships: [
        { rel_type: "RUNS_ON", to_type: "SaaSPlatform", to_key: "saas-servicenow", to_name: "ServiceNow Now Assist" }
      ]
    }
  ].map((o) => ({ ...o, tenant_id: tenantId, observed_at: now }));
}
